<a href="https://colab.research.google.com/github/Payal2330/data_science_lab_75/blob/main/pr_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 3x3 matrix
A = np.array([
    [2, 1, 3],
    [0, -1, 4],
    [5, 2, 0]
])

# Compute determinant
det_A = np.linalg.det(A)

print("Matrix A:\n", A)
print("Determinant of A:", det_A)

Matrix A:
 [[ 2  1  3]
 [ 0 -1  4]
 [ 5  2  0]]
Determinant of A: 18.999999999999996


In [2]:
import numpy as np

# Define the matrix
A = np.array([
    [2, 1, 3],
    [0, -1, 4],
    [5, 2, 0]
])

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Matrix A:\n", A)
print("\nInverse of A:\n", A_inv)

Matrix A:
 [[ 2  1  3]
 [ 0 -1  4]
 [ 5  2  0]]

Inverse of A:
 [[-0.42105263  0.31578947  0.36842105]
 [ 1.05263158 -0.78947368 -0.42105263]
 [ 0.26315789  0.05263158 -0.10526316]]


In [3]:
import numpy as np

# Coefficient matrix
A = np.array([
    [2, 3],
    [4, 5]
])

# Constant terms
B = np.array([10, 20])

# Solve the system
solution = np.linalg.solve(A, B)

x, y = solution

print("x =", x)
print("y =", y)

x = 5.0
y = 0.0
